name: "Deploy Nightly"

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
        
  nightly: 
    name: Deploy nightly
    runs-on: "ubuntu-latest"
    container: "marijnstevens/yagna-aarch64-build-system"
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      
      - name: Stamp nightly-tag
        uses: EndBug/latest-tag@latest
        with:
          tag-name: nightly
          description: Update nightly tag.

      - run: ./init-submodules.sh
      
      - name: "yagna"
        run: ./build.sh yagna
            
      - name: "ya-runtime-vm"
        run: ./build.sh ya-runtime-vm
      
      - name: "ya-runtime-wasi"
        run: ./build.sh ya-runtime-wasi
          
      - run: ./build-release-artifact.sh
                    
      - name: Upload Artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: app
          path:  yagna.tar.gz
